# Generated by Django 3.0.4 on 2020-03-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Pronouns', models.CharField(max_length=50)),
                ('Bio', models.CharField(max_length=1000)),
                ('Birthday', models.DateField()),
                ('Profile_pic', models.ImageField(upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('Followers', models.ManyToManyField(blank=True, to='fallendoverender.profile')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_text', models.CharField(max_length=1000)),
                ('Pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('Likes', models.ManyToManyField(blank=True, related_name='wholiked', to='fallendoverender.profile')),
                ('Posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='fallendoverender.profile')),
                ('Reblog_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fallendoverender.post')),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Media', models.FileField(upload_to='post_Media/', verbose_name='Media')),
                ('Medias_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fallendoverender.post')),
            ],
        ),
    ]
